version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redditdb

  app:
    build:
      dockerfile: Dockerfile
      target: dev
    environment:
      - DATABASE_URL=$DOCKER_DB_URL
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app